[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:zenbpm]
command=/app/zenbpm/zenbpm
directory=/app/zenbpm
environment=PROFILE=%(ENV_PROFILE)s,CONFIG_FILE=%(ENV_CONFIG_FILE)s
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/zenbpm.err.log
stdout_logfile=/var/log/supervisor/zenbpm.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:minio-adapter]
command=/app/minio-adapter/minio-adapter
directory=/app/minio-adapter
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/minio-adapter.err.log
stdout_logfile=/var/log/supervisor/minio-adapter.out.log
